app/base/models.py
from flask_login import UserMixin
from sqlalchemy import Binary, Column, Integer, String

from app import db, login_manager

from app.base.util import hash_pass

class User(db.Model, UserMixin):

    __tablename__ = 'User'

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True)
    email = Column(String, unique=True)
    password = Column(Binary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass( value ) # we need bytes here (not plain str)
                
            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None

app/base/forms.py
from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = TextField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = TextField('Username'     , id='username_create' , validators=[DataRequired()])
    email    = TextField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

app/base/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

app/base/routes.py
from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User

from app.base.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:
        
        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = User.query.filter_by(username=username).first()
        
        # Check the password
        if user and verify_pass( password, user.password):

            login_user(user)
            return redirect(url_for('base_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template( 'accounts/login.html', msg='Wrong user or password', form=login_form)

    if not current_user.is_authenticated:
        return render_template( 'accounts/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username  = request.form['username']
        email     = request.form['email'   ]

        # Check usename exists
        user = User.query.filter_by(username=username).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Username already registered',
                                    success=False,
                                    form=create_account_form)

        # Check email exists
        user = User.query.filter_by(email=email).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Email already registered', 
                                    success=False,
                                    form=create_account_form)

        # else we can create the user
        user = User(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template( 'accounts/register.html', 
                                msg='User created please <a href="/login">login</a>', 
                                success=True,
                                form=create_account_form)

    else:
        return render_template( 'accounts/register.html', form=create_account_form)

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('page-403.html'), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('page-403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('page-404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('page-500.html'), 500

app/base/templates/accounts/login.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
    <div class="col-md-8">
      <div class="card">

        <form role="form" method="post" action="">
        
          {{ form.hidden_tag() }} 

          <div class="card-header">
            <h5 class="title">Login</h5>

            <h6 class="card-category">
                {% if msg %}
                  <span class="text-danger">{{ msg | safe }}</span>
                {% else %}
                <span>
                  Add your credentials
                </span>
                {% endif %}  
            </h6>
          </div>

          <div class="card-body">

              <div class="row">

                <div class="col-md-3 px-md-1">
                  <div class="form-group">
                    <label>Username</label>
                    {{ form.username(class="form-control") }}
                  </div>
                </div>

              </div>
              <div class="row">

                <div class="col-md-3 px-md-1">
                  <div class="form-group">
                    <label>Password</label>
                    {{ form.password(class="form-control", type="password") }}
                  </div>
                </div>

              </div>
              
          </div>
          <div class="card-footer">
            <button type="submit" name="login" class="btn btn-fill btn-primary">Login</button>
            &nbsp; &nbsp;
            Don't have an account? <a href="{{ url_for('base_blueprint.register') }}" class="text-primary">Create</a>
          </div>

        </form>

      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/base/templates/accounts/page-user.html
{% extends "layouts/base.html" %}

{% block title %} Page User {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
  <div class="col-md-8">
    <div class="card">
      <div class="card-header">
        <h5 class="title">Edit Profile</h5>
          <h6 class="card-category">
                {% if msg %}
                  <span class="text-danger">{{ msg | safe }}</span>
                {% endif %}
          </h6>
      </div>
      <div class="card-body">
          <form role="form" method="get|post" action="">
          <div class="row">
            <div class="col-md-1 px-md-1">
              <div class="form-group">
                <label>UserID</label>
                {{ form.id(class="form-control") }}
              </div>
            </div>
            <div class="col-md-3 px-md-1">
              <div class="form-group">
                <label>Username</label>
                {{ form.username(class="form-control") }}
              </div>
            </div>
            <div class="col-md-3 px-md-1">
              <div class="form-group">
                <label>Password</label>
                {{ form.password(class="form-control", type="password") }}
              </div>
            </div>
            <div class="col-md-4 pl-md-1">
              <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                {{ form.email(class="form-control", type="email") }}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-5 pr-md-1">
              <div class="form-group">
                <label>First Name</label>
                {{ form.first_name(class="form-control") }}
              </div>
            </div>
            <div class="col-md-2 px-md-1">
              <div class="form-group">
                <label>Middle Initial</label>
                {{ form.middle_initial(class="form-control") }}
              </div>
            </div>
            <div class="col-md-5 pl-md-1">
              <div class="form-group">
                <label>Last Name</label>
                {{ form.last_name(class="form-control") }}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12, pr-md-1">
              <div class="form-group">
                <label>Date of Birth</label>
                {{ form.dob(class="form-control"), type="date" }}
              </div>
            </div>
          </div>
          <div class="row">
            <h6 class="title">Dose #1</h6>
          </div>
          <div class="row">
            <div class="col-md-3 pr-md-1">
              <div class="form-group">
                <label>Product Name/Manufacturer</label>
                {{ form.dose_1_product_name_manufacturer(class="form-control") }}
              </div>
            </div>
            <div class="col-md-3 px-md-1">
              <div class="form-group">
                <label>Lot Number</label>
                {{ form.dose_1_lot_number(class="form-control") }}
              </div>
            </div>
            <div class="col-md-3 pl-md-1">
              <div class="form-group">
                <label>Date</label>
                {{ form.dose_1_date(class="form-control"), type="date" }}
              </div>
            </div>
            <div class="col-md-3 pl-md-1">
              <div class="form-group">
                <label>Healthcare Professional or Clinic Site</label>
                {{ form.dose_1_healthcare_professional_or_clinic_site(class="form-control") }}
              </div>
            </div>
          </div>
          <div class="row">
            <h6 class="title">Dose #2</h6>
          </div>
          <div class="row">
            <div class="col-md-3 pr-md-1">
              <div class="form-group">
                <label>Product Name/Manufacturer</label>
                {{ form.dose_2_product_name_manufacturer(class="form-control") }}
              </div>
            </div>
            <div class="col-md-3 px-md-1">
              <div class="form-group">
                <label>Lot Number</label>
                {{ form.dose_2_lot_number(class="form-control") }}
              </div>
            </div>
            <div class="col-md-3 pl-md-1">
              <div class="form-group">
                <label>Date</label>
                {{ form.dose_2_lot_number(class="form-control"), type="date" }}
              </div>
            </div>
            <div class="col-md-3 pl-md-1">
              <div class="form-group">
                <label>Healthcare Professional or Clinic Site</label>
                {{ form.dose_2_healthcare_professional_or_clinic_site(class="form-control") }}
              </div>
            </div>
          </div>
          <div class="row">
            <h6 class="title">Dose #3</h6>
          </div>
          <div class="row">
            <div class="col-md-3 pr-md-1">
              <div class="form-group">
                <label>Product Name/Manufacturer</label>
                {{ form.dose_3_product_name_manufacturer(class="form-control") }}
              </div>
            </div>
            <div class="col-md-3 px-md-1">
              <div class="form-group">
                <label>Lot Number</label>
                {{ form.dose_3_lot_number(class="form-control") }}
              </div>
            </div>
            <div class="col-md-3 pl-md-1">
              <div class="form-group">
                <label>Date</label>
                {{ form.dose_3_date(class="form-control"), type="date" }}
              </div>
            </div>
            <div class="col-md-3 pl-md-1">
              <div class="form-group">
                <label>Healthcare Professional or Clinic Site</label>
                {{ form.dose_3_healthcare_professional_or_clinic_site(class="form-control") }}
              </div>
            </div>
          </div>
          <div class="row">
            <h6 class="title">Dose #4</h6>
          </div>
          <div class="row">
            <div class="col-md-3 pr-md-1">
              <div class="form-group">
                <label>Product Name/Manufacturer</label>
                {{ form.dose_4_product_name_manufacturer(class="form-control") }}
              </div>
            </div>
            <div class="col-md-3 px-md-1">
              <div class="form-group">
                <label>Lot Number</label>
                {{ form.dose_4_lot_number(class="form-control") }}
              </div>
            </div>
            <div class="col-md-3 pl-md-1">
              <div class="form-group">
                <label>Date</label>
                {{ form.dose_4_date(class="form-control"), type="date" }}
              </div>
            </div>
            <div class="col-md-3 pl-md-1">
              <div class="form-group">
                <label>Healthcare Professional or Clinic Site</label>
                {{ form.dose_4_healthcare_professional_or_clinic_site(class="form-control") }}
              </div>
            </div>
          </div>
        </form>
      </div>
      <div class="card-footer">
        <button type="submit" name="edit_profile" class="btn btn-fill btn-primary">Save</button>
      </div>
    </div>
    </div>
  <div class="col-md-4">
    <div class="card card-user">
      <div class="card-body">
        <p class="card-text">
          <div class="author">
            <div class="block block-one"></div>
            <div class="block block-two"></div>
            <div class="block block-three"></div>
            <div class="block block-four"></div>
            <a href="javascript:void(0)">
              <img class="avatar" src="/static/assets/img/emilyz.jpg" alt="Bill Gates photo - when buys a Linux.">
              <h5 class="title">
                {{ current_user.username }}
              </h5>
            </a>
            <p class="description">
              {{ current_user.email }}
            </p>
          </div>
        </p>
        <div class="card-description">
        </div>
      </div>
      <div class="card-footer">
        <div class="button-container">
          <button href="javascript:void(0)" class="btn btn-icon btn-round btn-facebook">
            <i class="fab fa-facebook"></i>
          </button>
          <button href="javascript:void(0)" class="btn btn-icon btn-round btn-twitter">
            <i class="fab fa-twitter"></i>
          </button>
          <button href="javascript:void(0)" class="btn btn-icon btn-round btn-google">
            <i class="fab fa-google-plus"></i>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/base/templates/accounts/register.html
{% extends "layouts/base.html" %}

{% block title %} Register {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
    <div class="col-md-8">
      <div class="card">

        <form role="form" method="post" action="">
        
          {{ form.hidden_tag() }} 

          <div class="card-header">
            <h5 class="title">Register</h5>

            <h6 class="card-category">
                {% if msg %}
                  <span class="text-danger">{{ msg | safe }}</span>
                {% else %}
                  Complete your credentials
                {% endif %}  
            </h6>
          </div>

          <div class="card-body">

              <div class="row">
                <div class="col-md-3 px-md-1">
                  <div class="form-group">
                    <label>Username</label>
                    {{ form.username(class="form-control") }}
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-3 px-md-1">
                  <div class="form-group">
                    <label>Email</label>
                    {{ form.email(class="form-control", type="email") }}
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-3 px-md-1">
                  <div class="form-group">
                    <label>Password</label>
                    {{ form.password(class="form-control", type="password") }}
                  </div>
                </div>
              </div>
              
          </div>
          <div class="card-footer">
            <button type="submit" name="register" class="btn btn-fill btn-primary">Register</button>
            &nbsp; &nbsp;
            Have an account? <a href="{{ url_for('base_blueprint.login') }}" class="text-primary">Login</a>
          </div>

        </form>

      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/base/templates/includes/fixed-plugin.html
  <div class="fixed-plugin">
    <div class="dropdown show-dropdown">
      <a href="#" data-toggle="dropdown">
        <i class="fa fa-cog fa-2x"> </i>
      </a>
      <ul class="dropdown-menu">
        <li class="header-title"> UI Color</li>
        <li class="adjustments-line">
          <a href="javascript:void(0)" class="switch-trigger background-color">
            <div class="badge-colors text-center">
              <span class="badge filter badge-primary active" data-color="primary"></span>
              <span class="badge filter badge-info" data-color="blue"></span>
              <span class="badge filter badge-success" data-color="green"></span>
            </div>
            <div class="clearfix"></div>
          </a>
        </li>
        <li class="adjustments-line text-center color-change">
          <span class="color-label">LIGHT MODE</span>
          <span class="badge light-badge mr-2"></span>
          <span class="badge dark-badge ml-2"></span>
          <span class="color-label">DARK MODE</span>
        </li>
        <li class="header-title">
            <a class="text-white" 
                      target="_blank" rel="noopener noreferrer" 
                      href="https://github.com/RoyalWeden/Vaccine-Spotter-And-Passport">Project VSAP</a>
        </li>
        <li>
          <br />
        </li>
      </ul>

    </div>
  </div>
  

app/base/templates/includes/footer.html
      <footer class="footer">
        <div class="container-fluid">
          <ul class="nav">
            <li class="nav-item">
              <a target="_blank" rel="noopener noreferrer"
                 href="https://github.com/RoyalWeden/Vaccine-Spotter-And-Passport" class="nav-link">
                Project VSAP
              </a>
            </li>
          </ul>
          <div class="copyright">
            <a target="_blank" rel="sponsored noopener noreferrer" 
                      href="https://jamhacks.ca/">Jamhacks V</a> 
          </div>
        </div>
      </footer>
      

app/base/templates/includes/navigation-rtl.html
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="javascript:void(0)">RTL</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse" id="navigation">
            <ul class="navbar-nav  mr-auto">
              <li class="search-bar input-group">
                <button class="btn btn-link" id="search-button" data-toggle="modal" data-target="#searchModal"><i class="tim-icons icon-zoom-split" ></i>
                  <span class="d-lg-none d-md-block">Search</span>
                </button>
              </li>
              <li class="dropdown nav-item">
                <a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="notification d-none d-lg-block d-xl-block"></div>
                  <i class="tim-icons icon-sound-wave"></i>
                  <p class="d-lg-none">
                    Notifications
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-menu-right dropdown-navbar">
                  <li class="nav-link"><a href="#" class="nav-item dropdown-item">Mike John responded to your email</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">You have 5 more tasks</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Your friend Michael is in town</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another notification</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another one</a></li>
                </ul>
              </li>
              <li class="dropdown nav-item">
                <a href="{{ url_for('base_blueprint.logout') }}" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="photo">
                    <img src="/static/assets/img/anime3.png" alt="Profile Photo">
                  </div>
                  <b class="caret d-none d-lg-block d-xl-block"></b>
                  <p class="d-lg-none">
                    Log out
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-navbar">
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Profile</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Settings</a></li>
                  <li class="dropdown-divider"></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Log out</a></li>
                </ul>
              </li>
              <li class="separator d-lg-none"></li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <i class="tim-icons icon-simple-remove"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- End Navbar -->

app/base/templates/includes/navigation.html
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
        <div class="container-fluid">
            <div class="navbar-wrapper">
                <div class="navbar-toggle d-inline">
                    <button type="button" class="navbar-toggler">
                        <span class="navbar-toggler-bar bar1"></span>
                        <span class="navbar-toggler-bar bar2"></span>
                        <span class="navbar-toggler-bar bar3"></span>
                    </button>
                </div>
                <a class="navbar-brand" ref="noopener noreferrer"
                   href="https://github.com/RoyalWeden/Vaccine-Spotter-And-Passport" class="nav-link">
                    Project VSAP
                </a>
            </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse" id="navigation">

            <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}

              <li class="search-bar input-group">
                <button class="btn btn-link" id="search-button" data-toggle="modal" data-target="#searchModal"><i class="tim-icons icon-zoom-split" ></i>
                  <span class="d-lg-none d-md-block">Search</span>
                </button>
              </li>
              <li class="dropdown nav-item">
                <a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="notification d-none d-lg-block d-xl-block"></div>
                  <i class="tim-icons icon-sound-wave"></i>
                  <p class="d-lg-none">
                    Notifications
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-menu-right dropdown-navbar">
                  <li class="nav-link"><a href="#" class="nav-item dropdown-item">Mike John responded to your email</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">You have 5 more tasks</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Your friend Michael is in town</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another notification</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another one</a></li>
                </ul>
              </li>
              <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="photo">
                    <img src="/static/assets/img/anime3.png" alt="Profile Photo">
                  </div>
                  <b class="caret d-none d-lg-block d-xl-block"></b>
                  <p class="d-lg-none">
                    Log out
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-navbar">
                  <li class="nav-link"><a href="/page-user.html" class="nav-item dropdown-item">Profile</a></li>
                  <li class="dropdown-divider"></li>
                  <li class="nav-link"><a href="{{ url_for('base_blueprint.logout') }}" class="nav-item dropdown-item">Log out</a></li>
                </ul>
              </li>
              <li class="separator d-lg-none"></li>

            {% endif %}  
            </ul>

          </div>
        </div>
      </nav>
      <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <i class="tim-icons icon-simple-remove"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- End Navbar -->

app/base/templates/includes/sidebar.html
    <div class="sidebar">
      <div class="sidebar-wrapper">
        <div class="logo">
            <a target="_self" rel="sponsored noopener noreferrer"
               href="/" class="simple-text logo-mini">
              ≡
            </a>
          <a target="_self" rel="sponsored noopener noreferrer" 
             href="/" class="simple-text logo-normal">
            MENU
          </a>
        </div>

        <ul class="nav">
            {% if current_user.is_authenticated %}

            <li class="{% if 'index' in segment %} active {% endif %}">
                <a href="/">
                    <i class="tim-icons icon-chart-pie-36"></i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li class="{% if 'icons' in segment %} active {% endif %}">
                <a href="/ui-icons.html">
                    <i class="tim-icons icon-atom"></i>
                    <p>Passport</p>
                </a>
            </li>
            <li class="{% if 'maps' in segment %} active {% endif %}">
                <a href="/ui-maps.html">
                    <i class="tim-icons icon-pin"></i>
                    <p>Spotter</p>
                </a>
            </li>
            <li class="{% if 'tools' in segment %} active {% endif %}">
                <a href="/tools.html">
                    <i class="tim-icons icon-settings"></i>
                    <p>Tools</p>
                </a>
            </li>
            <li class="{% if 'page-user' in segment %} active {% endif %}">
                <a href="/page-user.html">
                    <i class="tim-icons icon-single-02"></i>
                    <p>User Profile</p>
                </a>
            </li>
            <li>
                <a href="{{ url_for('base_blueprint.logout') }}">
                    <i class="tim-icons icon-button-power"></i>
                    <p>Logout</p>
                </a>
            </li>
            {% else %}
            {% endif %}

        </ul>
        
      </div>
    </div>